$(document).ready(function(){
  $('.collapsible').collapsible();
});
$(document).ready(function(){
  $('.materialboxed').materialbox();
});
$(document).ready(function(){
  $('.carousel').carousel();
});
$(document).ready(function(){
  $('.sidenav').sidenav();
});
$(document).ready(function(){
  $('.slider').slider();
});
